services:
  db:
    image: postgres:15-alpine
    container_name: lecsens-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: lecsens
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5444:5432"  # Ubah port external ke 5444
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d lecsens"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lecsens-network
    restart: unless-stopped

  app:
    build: .
    container_name: lecsens-app
    ports:
      - "3160:3160"
    environment:
      DB_HOST: db
      DB_PORT: 5432  # Port internal tetap 5432
      DB_USER: root
      DB_PASSWORD: P@ssw0rd
      DB_NAME: lecsens
      PORT: 3160
      GIN_MODE: release
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lecsens-network
    restart: unless-stopped

networks:
  lecsens-network:
    name: be-lecsens_network
    driver: bridge

volumes:
  pgdata:
    name: be-lecsens_pgdata