services:
  db:
    image: postgres:15-alpine
    container_name: asset-management-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: asset_management
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d asset_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - asset-management-network
    restart: unless-stopped

  app:
    build: .
    container_name: be-lecsens-asset-management
    ports:
      - "3122:3122"
    env_file:
      - .env
    volumes:
      - ${PWD}/.env:/app/.env:ro
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      AUTO_SEED: ${AUTO_SEED:-false}
      FORCE_RESEED: ${FORCE_RESEED:-false}
      PORT: ${PORT:-3122}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-P@ssw0rd}
      DB_NAME: ${DB_NAME:-asset_management}
      TENANT_API_URL: ${TENANT_API_URL:-https://lecsens-iot-api.erplabiim.com/api/external/tenants}
      TENANT_API_KEY: ${TENANT_API_KEY:-your-tenant-api-key-here}
      USER_API_URL: ${USER_API_URL:-https://lecsens-iot-api.erplabiim.com}
      USER_API_KEY: ${USER_API_KEY:-your-user-api-key-here}
      USER_AUTH_VALIDATE_TOKEN_ENDPOINT: ${USER_AUTH_VALIDATE_TOKEN_ENDPOINT:-/api/external/auth/validate-token}
      USER_AUTH_USER_INFO_ENDPOINT: ${USER_AUTH_USER_INFO_ENDPOINT:-/api/external/auth/user-info}
      USER_AUTH_VALIDATE_PERMISSIONS_ENDPOINT: ${USER_AUTH_VALIDATE_PERMISSIONS_ENDPOINT:-/api/external/auth/validate-user-permissions}
      USER_AUTH_VALIDATE_SUPERADMIN_ENDPOINT: ${USER_AUTH_VALIDATE_SUPERADMIN_ENDPOINT:-/api/external/auth/validate-superadmin}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      JWT_ISSUER: ${JWT_ISSUER:-asset-management-service}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-60}
      JWT_DEBUG: ${JWT_DEBUG:-false}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-dqfjr8qyw}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-643641237613514}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-MxS4J3fxIhp_JhllOl7m3pAkOEE}
      GIN_MODE: ${GIN_MODE:-release}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asset-management-network
    restart: unless-stopped

networks:
  asset-management-network:
    name: asset-management_network
    driver: bridge

volumes:
  pgdata:
    name: asset-management_pgdata
